name: Auto Generate PR Description

on:
  pull_request:
    types: [opened]

jobs:
  auto-generate-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Run PR description generation script
        run: |
          cd .github/worksflows/pr_workflow
          ./create_pr.sh
